Repository pagopa/pagopa-fdr-technical-support, pull requests merged in 2023-09, with the labels that each got.

#4 feat: api2 and api3
  .quarkus/cli/plugins/quarkus-cli-catalog.json
  postman-collection/API Assistenza Fdr.postman_collection.json
  src/main/java/it/gov/pagopa/fdrtechsupport/clients/FdrOldRestClient.java
  src/main/java/it/gov/pagopa/fdrtechsupport/clients/FdrRestClient.java
  src/main/java/it/gov/pagopa/fdrtechsupport/repository/model/FdrEventEntity.java
  src/main/java/it/gov/pagopa/fdrtechsupport/resources/PspResource.java
  src/main/java/it/gov/pagopa/fdrtechsupport/resources/response/FdrFullInfoResponse.java
  src/main/java/it/gov/pagopa/fdrtechsupport/resources/response/FrResponse.java
  src/main/java/it/gov/pagopa/fdrtechsupport/service/WorkerService.java
  src/main/openapi/api_fdr.json
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/fdrtechsupport/resources/GenericTest.java
  src/test/java/it/gov/pagopa/fdrtechsupport/resources/GetByPspAndIurTest.java
  src/test/java/it/gov/pagopa/fdrtechsupport/resources/GetByPspAndIuvTest.java
  src/test/resources/mockserver.properties
  src/test/resources/mockserver/cache.json
Labels: size/large

#5 [NOD-443] OpenAPI
  mvnw
  openapi/openapi.json
Labels: size/small

#6 bump semver
  .github/workflows/check_pr.yml
  README.md
Labels: size/small, breaking-change

#9 Nod 419 recupero xml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  postman-collection/API Assistenza Fdr.postman_collection.json
  src/main/java/it/gov/pagopa/fdrtechsupport/clients/FdrOldRestClient.java
  src/main/java/it/gov/pagopa/fdrtechsupport/clients/FdrRestClient.java
  src/main/java/it/gov/pagopa/fdrtechsupport/exceptions/AppErrorCodeMessageEnum.java
  src/main/java/it/gov/pagopa/fdrtechsupport/models/FdrBaseInfo.java
  src/main/java/it/gov/pagopa/fdrtechsupport/repository/FdrTableRepository.java
  src/main/java/it/gov/pagopa/fdrtechsupport/repository/model/FdrEventEntity.java
  src/main/java/it/gov/pagopa/fdrtechsupport/resources/OrgResource.java
  src/main/java/it/gov/pagopa/fdrtechsupport/resources/PspResource.java
  src/main/java/it/gov/pagopa/fdrtechsupport/service/WorkerService.java
  src/test/java/it/gov/pagopa/fdrtechsupport/resources/GetByPspAndIurTest.java
  src/test/java/it/gov/pagopa/fdrtechsupport/resources/GetByPspAndIuvTest.java
  src/test/java/it/gov/pagopa/fdrtechsupport/util/AppConstantTestHelper.java
Labels: size/large

#10 fix query table storage
  src/main/java/it/gov/pagopa/fdrtechsupport/repository/FdrTableRepository.java
Labels: size/small

#12 fix
  .github/workflows/04h_deploy_with_github_runner.yml
Labels: ignore-for-release

#13 fix
  .identity/00_data.tf
  .identity/03_github_environment.tf
Labels: ignore-for-release

#14 fix
  .github/workflows/04_release_deploy.yml
Labels: ignore-for-release

#15 fix: updated Notify pipeline
  .github/workflows/04_release_deploy.yml
  .gitignore
  .identity/.terraform.lock.hcl
Labels: size/small, ignore-for-release
